version: "3.3"
services:
  ipfs:
    container_name: moniswap-ipfs-service
    image: ipfs/kubo:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./ipfs/config.sh:/container-init.d/config.sh
      - ipfs--data:/ipfsdata
    networks:
      - graph
  postgres:
    container_name: moniswap-graphs-db
    image: postgres
    networks:
      - graph
    command:
      [
        "postgres",
        "-cmax_connections=1000",
        "-cshared_preload_libraries=pg_stat_statements",
      ]
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - postgres--data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=bsc_testnet_db,bera_mainnet_db
  bsc-testnet:
    container_name: bsc_testnet_graph
    image: graphprotocol/graph-node
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: postgres
      postgres_pass: postgres
      postgres_db: bsc_testnet_db
      ipfs: ipfs:5001
      ethereum: "bscTestnet:https://data-seed-prebsc-1-s1.binance.org:8545"
      GRAPH_LOG: info
      ETHEREUM_POLLING_INTERVAL: 5000
    networks:
      - graph
  proxy:
    container_name: graph_nodes_proxy
    networks:
      - graph
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 65000:80
    depends_on:
      - bsc-testnet
      - ipfs
networks:
  graph:
    external: false
volumes:
  postgres--data:
    external: false
  ipfs--data:
    external: false
